### PR TITLE
Adding support for graphite plaintext protocol.

### PR DESCRIPTION
**Pull request by thomasplarsson**
Title says it.

This is useful at my company since those who host our graphite have turned off the pickle port.
I thought that perhaps this might be the fact at other places as well.

Best Regards
/Thomas

### CODE REVIEW

**Comment by roiravhon** [comment]
Thanks for that @Thoymas!
Looks good. Did you test the change?

Thanks,
Roi

**Comment by thomasplarsson** [comment]
Yep. Tested it using the https://github.com/obfuscurity/synthesize vagrant graphite vm and pulling data from our dev elk cluster. Haven't seen any problems.

**Comment by roiravhon** [comment]
Awesome. I'll set up an internal test as well, and I'll merge and push to docker hub.

**Comment by thomasplarsson** [comment]
Nice. Could you write something here when it's on docker hub?

**Comment by roiravhon** [comment]
Of course

**Comment by roiravhon** [comment]
Thanks @Thoymas, merged and pushed to docker hub. Sorry for the delay

**Pull request merged**
