### PR TITLE
Put environmental variables into namespace to prevent conflicts

### PR DESCRIPTION
**Pull request by benmathews**
As noted in the issue I filed, I'm running this in kubernetes and it is populating an environmental variable that conflicts with what this previously assumed.

### CODE REVIEW

**Comment by roiravhon** [comment]
Thanks @benmathews!
I have a slight problem with this PR, as it will break all containers people are currently using when pulling the new version.

Maybe have any other suggestion?
The easiest solution will be changing namespace in k8s.
Is your ES cluster running on your k8s cluster?

**Comment by benmathews** [comment]
Lack of versioning was something else I noticed. It is always good practice to version images precisely to allow breaking changes. Perhaps we could version the image to preserve the old names structure and then pull in this with a new version? 

On the suggested change, it seems a real impediment to using the tool in kubernetes to have the environmental variables potentially conflicting like they do. I could as you suggest put elasticsearch and es2graphite in different namespaces. But that seems a hack that makes my environment less understandable and maintainable instead of doing what IMO is the right and easy fix.

**Comment by roiravhon** [comment]
The naming convention never ends though.
What happens if I have a container named es2graphite_elasticsearch?
WDYS about passing parameters in the CMD?

And about versioning, you are right.
We will start using it from the next release, but unfortunately, :latest will still be updated so the compatibility will break

**Comment by benmathews** [comment]
I guess you would be out of luck with that name. :) Passing command line arguments would work great. I was trying to respect the way you had set up the program.

**Comment by roiravhon** [comment]
Always open to changes, as long as they are not breaking anything :)
Are you PR-ing this?
It should default to environment variables (at least for now, as :latest will change) and if they are not present, go to CMD arguments

**Comment by benmathews** [comment]
This pull request was a solution to my problem that I'm happy to offer up. If you want to go another direction, that is fine. I've got something that works and I'll leave it alone from here.

**Comment by roiravhon** [comment]
Closing for now

**Pull request closed without merging**
