### PR TITLE
add basic auth and https options to es2graphite

### PR DESCRIPTION
**Pull request by evanvolgas**
This adds https and basic auth support to es2graphite. It also reorders imports because my linter is picky like that and I don't have the energy to fight with it.

### CODE REVIEW

**Comment by roiravhon** [comment]
Hey @evanv and thanks for the PR!
Just making sure, did you test your change?

Can you please also update the documentation?

Thanks,
Roi.

**Comment by evanvolgas** [comment]
I did test my change yes. I'd love another set of eyes though. Actually putting this into prod on a few clusters later today so that'll give me a chance to find any gross bugs. I'll circle back today/tomorrow with updated docs and bug fixes if any become necessary. Tested on clusters with and without auth and didn't have any issues though. Pretty sure this is okay.

**Comment by roiravhon** [comment]
Thanks. I'll be waiting for your report here.
And of course, I'll run my tests as well before merging.

**Comment by evanvolgas** [comment]
I had to rip out the pickle bits cause our carbon relay doesn't support pickle... but the parts that I am adding here worked fine. As much as I can test it, I have.... but I don't have easy access to a carbon relay that accepts pickle. Do you mind testing that part? As long as you see no issues, I think this is safe to merge. I also updated the readme.

**Comment by roiravhon** [comment]
Thanks.
Ill set up a test soon and merge

**Comment by roiravhon** [comment]
Pushed to docker hub.

Thanks a lot for this PR @evanv!

**Comment by evanvolgas** [comment]
Thanks for grabbing it. Got a few more things I want to add -- cluster and task endpoints, etc. Will have a few follow up PRs in the next few weeks.

**Comment by roiravhon** [comment]
You are more than welcome!
Thanks :)

**Pull request merged**
